/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('tdesign-icons-vue-next')['AddIcon']
    BrowseOffIcon: typeof import('tdesign-icons-vue-next')['BrowseOffIcon']
    CaretDownSmallIcon: typeof import('tdesign-icons-vue-next')['CaretDownSmallIcon']
    Edit1Icon: typeof import('tdesign-icons-vue-next')['Edit1Icon']
    FileCopyIcon: typeof import('tdesign-icons-vue-next')['FileCopyIcon']
    LocationIcon: typeof import('tdesign-icons-vue-next')['LocationIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('tdesign-icons-vue-next')['SearchIcon']
    SettingIcon: typeof import('tdesign-icons-vue-next')['SettingIcon']
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar']
    TBadge: typeof import('tdesign-mobile-vue')['Badge']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TCheckTag: typeof import('tdesign-mobile-vue')['CheckTag']
    TConfigProvider: typeof import('tdesign-mobile-vue')['ConfigProvider']
    TDateTimePicker: typeof import('tdesign-mobile-vue')['DateTimePicker']
    TDivider: typeof import('tdesign-mobile-vue')['Divider']
    TFab: typeof import('tdesign-mobile-vue')['Fab']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TGrid: typeof import('tdesign-mobile-vue')['Grid']
    TGridItem: typeof import('tdesign-mobile-vue')['GridItem']
    TIcon: typeof import('tdesign-mobile-vue')['Icon']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TLoading: typeof import('tdesign-mobile-vue')['Loading']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TPicker: typeof import('tdesign-mobile-vue')['Picker']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TProgress: typeof import('tdesign-mobile-vue')['Progress']
    TPullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh']
    TRadio: typeof import('tdesign-mobile-vue')['Radio']
    TRadioGroup: typeof import('tdesign-mobile-vue')['RadioGroup']
    TResult: typeof import('tdesign-mobile-vue')['Result']
    TSearch: typeof import('tdesign-mobile-vue')['Search']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTable: typeof import('tdesign-mobile-vue')['Table']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
    TTextarea: typeof import('tdesign-mobile-vue')['Textarea']
    TUpload: typeof import('tdesign-mobile-vue')['Upload']
    UploadIcon: typeof import('tdesign-icons-vue-next')['UploadIcon']
    UserIcon: typeof import('tdesign-icons-vue-next')['UserIcon']
    ViewListIcon: typeof import('tdesign-icons-vue-next')['ViewListIcon']
  }
}
