/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TCheckbox: typeof import('tdesign-mobile-vue')['Checkbox']
    TCheckboxGroup: typeof import('tdesign-mobile-vue')['CheckboxGroup']
    TConfigProvider: typeof import('tdesign-mobile-vue')['ConfigProvider']
    TDateTimePicker: typeof import('tdesign-mobile-vue')['DateTimePicker']
    TDivider: typeof import('tdesign-mobile-vue')['Divider']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TNavBar: typeof import('tdesign-mobile-vue')['NavBar']
    TPicker: typeof import('tdesign-mobile-vue')['Picker']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TRadio: typeof import('tdesign-mobile-vue')['Radio']
    TRadioGroup: typeof import('tdesign-mobile-vue')['RadioGroup']
    TTextarea: typeof import('tdesign-mobile-vue')['Textarea']
    TUpload: typeof import('tdesign-mobile-vue')['Upload']
  }
}
