/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar']
    TBadge: typeof import('tdesign-mobile-vue')['Badge']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TCheckbox: typeof import('tdesign-mobile-vue')['Checkbox']
    TCheckTag: typeof import('tdesign-mobile-vue')['CheckTag']
    TConfigProvider: typeof import('tdesign-mobile-vue')['ConfigProvider']
    TDateTimePicker: typeof import('tdesign-mobile-vue')['DateTimePicker']
    TDivider: typeof import('tdesign-mobile-vue')['Divider']
    TDropdownItem: typeof import('tdesign-mobile-vue')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-mobile-vue')['DropdownMenu']
    TFab: typeof import('tdesign-mobile-vue')['Fab']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TGrid: typeof import('tdesign-mobile-vue')['Grid']
    TGridItem: typeof import('tdesign-mobile-vue')['GridItem']
    TIcon: typeof import('tdesign-mobile-vue')['Icon']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TLink: typeof import('tdesign-mobile-vue')['Link']
    TLoading: typeof import('tdesign-mobile-vue')['Loading']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TPicker: typeof import('tdesign-mobile-vue')['Picker']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TProgress: typeof import('tdesign-mobile-vue')['Progress']
    TPullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh']
    TRadio: typeof import('tdesign-mobile-vue')['Radio']
    TRadioGroup: typeof import('tdesign-mobile-vue')['RadioGroup']
    TSearch: typeof import('tdesign-mobile-vue')['Search']
    TSkeleton: typeof import('tdesign-mobile-vue')['Skeleton']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
    TTable: typeof import('tdesign-mobile-vue')['Table']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
    TTextarea: typeof import('tdesign-mobile-vue')['Textarea']
    TUpload: typeof import('tdesign-mobile-vue')['Upload']
  }
}
